### ISSUE TITLE
Lot of warnings when run 'rake test' w/minitest

### ISSUE THREAD

**Issue by darkslategrey** [hanami/utils#123]
ruby version : 2.3.0 within rbenv
hanami version : 0.7
Complete logs : https://gist.github.com/darkslategrey/deade748d3c5ecea450d

To diable warnings when running `rake test` add `$VERBOSE=nil` into your `spec/spec_helper.rb`

**Comment by hirokiraj** [comment]
Same thing happening with RVM and ruby-2.2.0, using Hanami in 0.7.2 version

**Comment by jodosha** [comment]
@darkslategrey @hirokiraj Hi and thanks for starting this discussion.

We haven't developed the framework with warnings enabled. That suddenly became a problem with Rake 11 because it turns on Ruby warnings by default.

---

The task isn't solvable with a single PR. There are several cases to take in account:

  * Poor Ruby usage: see the `*attributes` example above
  * Circular dependencies
  * Deprecated Ruby features without a clear replacement: `URI.extract` and `URI.escape`.
  * Third party gems that we depend on

---

My suggestion is to proceed like this:

  * For each repository, bump the development dependency to Rake 11. This will allow to see the warnings.
  * For each case spotted, open a ticket with the `ruby-warnings` label.

---

I'm gonna close this ticket because its scope is too wide.

**Comment by ericfreese** [comment]
Another potential workaround for this would be to disable warnings in the rake test task setup:

```diff
diff --git a/Rakefile b/Rakefile
index 554937b..dc2dcf0 100644
--- a/Rakefile
+++ b/Rakefile
@@ -5,6 +5,7 @@ require 'rake/testtask'
 Rake::TestTask.new do |t|
   t.pattern = 'spec/**/*_spec.rb'
   t.libs    << 'spec'
+  t.warning = false
 end
 
 task default: :test
```
