### ISSUE TITLE
Hanami::Interactor and sorbet signature raise an exception

### ISSUE THREAD

**Issue by heragu** [hanami/utils#393]
Assuming you have a project with `hanami-utils` and `sorbet` setup:

```
class MyInteractor
  include Hanami::Interactor

  extend T::Sig

  sig { params(a: Hash) }
  def call(a)
    true
  end
end

MyInteractor.new.call({})
```

It raises:

```
RuntimeError:
   You're trying to replace `call` on `MyInteractor`, but that method exists in a prepended module (Hanami::Interactor::Interface), which we don't currently support. Talk to #dev-productivity for help.
```

It is debatable if it is a bug on Hanami::Interactor or in Sorbet runtime :D

For me is more an error on Hanami::Interactor and that is why I am opening the bug issue here. What do you think?

**Comment by cllns** [comment]
Hi, sorry the interactor isn't working with `sorbet`. It was created before sorbet so we didn't anticipate this. While I think generally we're interested in supporting type signatures in Hanami, this library is a bit old and I don't think we're interested in re-working the internals right now. This is because `Hanami::Interactor` will go away in Hanami 2 (which is what our efforts are focused on right now).

I recommend using [`dry-transaction`](https://dry-rb.org/gems/dry-transaction/0.13/) instead as a relatively close replacement for `Hanami::Interactor`. Also, [`dry-monads`](https://dry-rb.org/gems/dry-monads/1.3/) presents a pretty different approach (I recommend checking out `Do` notation for it), which is a bit more to learn but might be worth it for you.

We may create a lightweight zero-configuration `Hanami::Operation` for ease of use, but that'll be based on `dry-monads`.

Closing this 🌸  I'm not sure if it's a bug in `sorbet`, but I don't consider it a bug in `Hanami::Interactor`, since we haven't said it should work with sorbet. It seems like it's more of an implementation tradeoff they made.
